version: "3.7"

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:7000"
    volumes:
      - "./:/code/"
    ports:
      - 7000:7000
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
#  chrome_standalone:
#    restart: always
#    image: selenium/standalone-chrome-debug:latest
#    volumes:
#      - /dev/shm:/dev/shm
#    ports:
#      - 1111:4444
#      - "5900"
#    stdin_open: true

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

